gBirchSpeech_Welcome:: @ 81C6D78
	.string "Hi! Sorry to keep you waiting!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p$"

gBirchSpeech_ThisIsPokemon:: @ 81C6DF8
	.string "So you wanna be a master?\p$"

gBirchSpeech_WorldInhabitedByPokemon:: @ 81C6E1A
	.string "Where is your God now,\n"
	.string "MOTHERFUCKER?!!!!!!!!\p$"

gBirchSpeech_AndYouAre:: @ 81C6FCB
	.string "And you are?$"

gBirchSpeech_AreYouBoyOrGirl:: @ 81C6FD8
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gBirchSpeech_WhatsYourName:: @ 81C6FFA
	.string "All right.\n"
	.string "What’s your name?$"

gBirchSpeech_SoItsPlayer:: @ 81C7017
	.string "So it’s {PLAYER}{KUN}?$"

gBirchSpeech_AhOkayYouArePlayer:: @ 81C7025
	.string "Ah, okay!\p"
	.string "You’re {PLAYER}{KUN} who’s moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!$"

gBirchSpeech_AreYouReady:: @ 81C7074
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I’ll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p$"
